# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    upload_to_play_store(track: 'beta',
    apk: '../build/app/outputs/apk/production/release/app-production-release.apk')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Upload to DeployGate"
  lane :dg do
    upload_to_deploygate(release_note: "通報機能追加")
  end

  private_lane :upload_to_deploygate do |params|
    releaseNote = params[:release_note]
    deploygate(
      apk: '../build/app/outputs/apk/production/release/app-production-release.apk',
      # message: "Fastlane build #{lane_context[SharedValues::BUILD_NUMBER]}",
      message: releaseNote,
      release_note: releaseNote,
      distribution_key: ENV["DEPLOYGATE_DISTRIBUTION_KEY_FOR_ANDROID"],
    )
  end
end
